# this file is the list of commands that can be used to run apps on docker rather than typing all of the commands individually
version: "3" 
services: 
    api:
    build: .
    depends_on:
        - postgres
    ports: 
        - 8000:8000
    # env_file:       instead of writing all of our variables out we can simply have this file point to our desired env file
    #     - ./.env 
    environment: 
        - DATABASE_HOSTNAME=postgres
        - DATABASE_PORT=5432
        - DATABASE_PASSWORD=Blackbird1195
        - DATABASE_NAME=fastapi
        - DATABASE_USERNAME=postgres
        - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        - ALGORITHUM=HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=fastapi
            - 
        volumes:
            - postgres-db:/var/lib/postgresql/data 
volumes: 
    postgres-db: