# this file is the list of commands that can be used to run apps on docker rather than typing all of the commands individually
version: "3" 
services: 
    api:
    image: # the name of the dockerhub repository image will go here 
    depends_on:
        - postgres
    ports: 
        - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --post 8000 
    # env_file:       instead of writing all of our variables out we can simply have this file point to our desired env file
    #     - ./.env 
    environment: 
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHUM=${ALGORITHUM}
        - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
            - 
        volumes:
            - postgres-db:/var/lib/postgresql/data 
volumes: 
    postgres-db: